version = 0.1
[default.deploy.parameters]
stack_name = "MichaelEinreinhofPetStore"
resolve_s3 = true
s3_prefix = "MichaelEinreinhofPetStore"
region = "us-east-1"
profile = "Jamf-Sandbox.AdministratorAccess"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
