AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for petstore

# create all Lambda functions with a 60 second timeout
Globals:
  Function:
    Timeout: 60
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512
    Architectures:
      - arm64

Resources:

  GetPetById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/GetPetById/GetPetById.zip
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/{petId}

  GetPetsByTags:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/GetPetsByTags/GetPetsByTags.zip
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbytags

  GetPetsByStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/GetPetsByStatus/GetPetsByStatus.zip
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbystatus

  UpdatePet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/UpdatePet/UpdatePet.zip
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: put
            Path: /pet

  AddPet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/AddPet/AddPet.zip
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: post
            Path: /pet


# print API endpoint and name of database table
Outputs:
  SwiftAPIEndpoint:
    Description: "API Gateway endpoint URL for your application"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
