name: OpenAPI Validate
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/openapi-lint.yaml
        with:
          openapi-file: Sources/openapi.yaml
          vacuum-version: v0.16.3
          go-version: 1.24.0
  
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Swift package archive
        run: swift package archive --allow-network-connections docker
      
      - name: Ensure SAM is installed
        uses: aws-actions/setup-sam@v2

      - name: Sam Build
        run: sam build
      
      - name: Start local API Gateway
        run: sam local start-api --template template.yml --disable-authorizer 2>&1 | tee sam_logs.txt

      - name: Stop SAM Local
        run: pkill -f "sam local start-api"